### ISSUE TITLE
[EPIC] Client Feedback

### ISSUE THREAD

**Issue by Potherca** [Peachey-Schoorl/schooltrui-vsz#1]
## Action required

The following point of feedback need to be resolved:

- [x] #6
  _Action by client by required_
- [x] #5
  _Action by client by required_
 - [x] #4
  _Action by client by required_
- [x] #7
  _Action by client by required_
- [x] #2
  _Action by client by required_

## Action without client involvement

- [x] The client would like QR code to the conversion page (where the sweater can be bought)
  _Stripe provides this:_ [Stripe Docs: Share QR Code ](https://stripe.com/docs/payment-links/share#create-qr-code)
 - [x] #3
  
##  Action by client by required

- [ ] Write text for underneath the CTA button
- [ ] Write text regarding delivery
- [x] Specify which shade of blue is needed (can be RGB, Hex, image, or whatever)
- [x] Specify font for price
  
The actions regarding font (and color?) might be easier to fine-tune together with the client.

## No action required yet

 - [x] The price _might_ change

**Comment by Potherca** [comment]
Closing this in favor of individual issues.
